# Generated by Django 3.1.3 on 2020-11-11 06:20

import Submission.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Assignments', '0002_sent_assignment'),
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('submission_file', models.FileField(blank=True, null=True, upload_to=Submission.models.submission_directory_path)),
                ('sent_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assignments.sent_assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=10)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Submission.submission')),
            ],
        ),
    ]
