# Generated by Django 3.1.3 on 2020-11-19 09:48

import Assignments.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Class', '0001_initial'),
        ('Instructors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('deadline', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('assignment_pdf', models.FileField(blank=True, null=True, upload_to=Assignments.models.assignment_directory_path)),
                ('input_test_cases', models.FileField(blank=True, null=True, upload_to=Assignments.models.input_directory_path)),
                ('output_test_cases', models.FileField(blank=True, null=True, upload_to=Assignments.models.output_directory_path)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructors.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Sent_Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assignments.assignment')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Class.section')),
            ],
        ),
    ]
