# Generated by Django 3.1.3 on 2020-11-05 05:08

import Assignments.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Instructors', '0003_instructor_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('deadline', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('assignment_pdf', models.FileField(blank=True, null=True, upload_to=Assignments.models.assignment_directory_path)),
                ('input_test_cases', models.FileField(blank=True, null=True, upload_to=Assignments.models.input_directory_path)),
                ('output_test_cases', models.FileField(blank=True, null=True, upload_to=Assignments.models.output_directory_path)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructors.instructor')),
            ],
        ),
    ]
