# Generated by Django 3.1.3 on 2020-11-11 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0004_auto_20201110_1600'),
        ('Assignments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sent_Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assignments.assignment')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Class.section')),
            ],
        ),
    ]
