# Generated by Django 3.1.3 on 2020-11-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0002_auto_20201030_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
