# Generated by Django 3.1.3 on 2020-11-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0001_initial'),
        ('Instructors', '0003_instructor_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='classes',
            field=models.ManyToManyField(to='Class.Class'),
        ),
    ]
