# Generated by Django 3.1.3 on 2020-11-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0003_auto_20201108_0502'),
        ('Instructors', '0004_instructor_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='classes',
            field=models.ManyToManyField(blank=True, null=True, to='Class.Class'),
        ),
    ]
